# Generated by Django 5.0.6 on 2024-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_book_first_chapter_id_book_last_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_chapter_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_chapter_id',
            field=models.IntegerField(default=0),
        ),
    ]
