# Generated by Django 5.0.6 on 2024-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_book_first_chapter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrecord',
            name='chapter_title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
